In [1]:
import pandas as pd
from nba_api.stats import endpoints as kobe
from nba_api.stats.static import players, teams
from nba_api.stats.library.parameters import Season

In [19]:
team_lineups = (
    kobe
    .teamdashlineups
    .TeamDashLineups(teams.get_teams()[0]['id'])
    .get_data_frames()
)

team_lineups[1].head()

,GROUP_SET,GROUP_ID,GROUP_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,Lineups,-203991-1629027-1630552-1630700-1642258-,C. Capela - T. Young - J. Johnson - D. Daniels...,9,4,5,0.444,103.631667,98,212,...,1,1,147,1,1,147,147,1,1,6
1,Lineups,-203991-1629027-1629726-1630552-1630700-,C. Capela - T. Young - G. Mathews - J. Johnson...,5,2,3,0.400,23.040000,26,47,...,2,2,146,3,13,146,145,2,2,1
2,Lineups,-203991-1629027-1629631-1630552-1630700-,C. Capela - T. Young - D. Hunter - J. Johnson ...,2,2,0,1.000,22.266667,21,43,...,2,3,142,2,2,143,138,3,3,2
3,Lineups,-1629726-1630168-1630552-1630811-1631223-,G. Mathews - O. Okongwu - J. Johnson - K. Wall...,4,1,3,0.250,17.616667,17,32,...,4,4,144,23,13,137,97,16,4,20
4,Lineups,-203991-1629027-1630552-1631223-1642258-,C. Capela - T. Young - J. Johnson - D. Roddy -...,2,0,2,0.000,17.150000,17,34,...,5,4,144,9,6,143,146,6,5,141

In [33]:
team_on_off_det = (
    kobe
    .teamplayeronoffdetails
    .TeamPlayerOnOffDetails(teams.get_teams()[0]['id'])
    .get_data_frames()
)

team_on_off_det[1].head()

,GROUP_SET,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,VS_PLAYER_ID,VS_PLAYER_NAME,COURT_STATUS,GP,W,L,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,On/Off Court,1610612737,ATL,Atlanta Hawks,1631230,"Barlow, Dominick",On,2,1,1,...,14,15,1,14,14,1,2,15,15,4
1,On/Off Court,1610612737,ATL,Atlanta Hawks,203992,"Bogdanović, Bogdan",On,1,1,0,...,13,13,3,13,12,3,3,13,13,3
2,On/Off Court,1610612737,ATL,Atlanta Hawks,203991,"Capela, Clint",On,12,5,7,...,5,5,10,5,6,12,11,5,5,10
3,On/Off Court,1610612737,ATL,Atlanta Hawks,1630700,"Daniels, Dyson",On,10,5,5,...,3,3,13,3,3,13,12,3,3,11
4,On/Off Court,1610612737,ATL,Atlanta Hawks,1631243,"Gueye, Mouhamed",On,2,0,2,...,14,14,1,15,14,1,1,14,14,2

In [34]:
team_on_off_sum = (
    kobe
    .teamplayeronoffsummary
    .TeamPlayerOnOffSummary(teams.get_teams()[0]['id'])
    .get_data_frames()
)

team_on_off_sum[1].head()

,GROUP_SET,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,VS_PLAYER_ID,VS_PLAYER_NAME,COURT_STATUS,GP,MIN,PLUS_MINUS,OFF_RATING,DEF_RATING,NET_RATING
0,On/Off Court,1610612737,ATL,Atlanta Hawks,1631230,"Barlow, Dominick",On,2,11.0,-22.4,53.8,79.2,-25.3
1,On/Off Court,1610612737,ATL,Atlanta Hawks,203992,"Bogdanović, Bogdan",On,1,28.0,-5.2,109.4,115.9,-6.5
2,On/Off Court,1610612737,ATL,Atlanta Hawks,203991,"Capela, Clint",On,12,267.0,-3.6,110.4,114.4,-4.0
3,On/Off Court,1610612737,ATL,Atlanta Hawks,1630700,"Daniels, Dyson",On,10,331.0,-3.8,110.3,114.3,-4.1
4,On/Off Court,1610612737,ATL,Atlanta Hawks,1631243,"Gueye, Mouhamed",On,2,11.0,-4.2,72.0,76.0,-4.0

In [45]:
franchise = (
    kobe
    .franchiseplayers
    .FranchisePlayers(teams.get_teams()[0]['id'])
    .get_data_frames()
)

franchise[0]

,LEAGUE_ID,TEAM_ID,TEAM,PERSON_ID,PLAYER,SEASON_TYPE,ACTIVE_WITH_TEAM,GP,FGM,FGA,...,FT_PCT,OREB,DREB,REB,AST,PF,STL,TOV,BLK,PTS
0,00,1610612737,Atlanta Hawks,1950,Andy Panko,Regular Season,0,1,0,0,...,0.000,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0
1,00,1610612737,Atlanta Hawks,78558,Mike Williams,Regular Season,0,5,0,4,...,0.000,0.0,1.0,1.0,0,2,0.0,0.0,0.0,0
2,00,1610612737,Atlanta Hawks,202719,Jeremy Tyler,Regular Season,0,1,0,0,...,0.000,0.0,3.0,3.0,0,0,0.0,0.0,0.0,0
3,00,1610612737,Atlanta Hawks,2321,Paul Shirley,Regular Season,0,2,0,4,...,0.000,0.0,1.0,1.0,0,0,0.0,0.0,0.0,0
4,00,1610612737,Atlanta Hawks,1627852,Nicolas Brussino,Regular Season,0,4,0,2,...,0.000,0.0,3.0,3.0,0,0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
580,00,1610612737,Atlanta Hawks,1631213,Tyrese Martin,Regular Season,0,16,9,23,...,1.000,5.0,7.0,12.0,2,2,1.0,2.0,0.0,21
581,00,1610612737,Atlanta Hawks,1631223,David Roddy,Regular Season,1,10,24,43,...,0.846,4.0,35.0,39.0,19,11,6.0,12.0,2.0,68
582,00,1610612737,Atlanta Hawks,1631230,Dominick Barlow,Regular Season,1,2,0,1,...,0.500,0.0,0.0,0.0,0,1,0.0,0.0,0.0,1
583,00,1610612737,Atlanta Hawks,1631243,Mouhamed Gueye,Regular Season,1,8,9,27,...,0.833,10.0,14.0,24.0,4,13,5.0,2.0,4.0,26
584,00,1610612737,Atlanta Hawks,1642258,Zaccharie Risacher,Regular Season,1,12,51,137,...,0.622,20.0,28.0,48.0,15,30,13.0,14.0,11.0,140