In [50]:
import pandas as pd
import snakecase
from requests import get
from nba_api.stats.endpoints import boxscoretraditionalv2, boxscoreadvancedv2
from nba_api.stats.static import players, teams
from nba_api.stats.library.parameters import Season
from dataHub import dataHub
from sqlalchemy.dialects.postgresql.base import PGDialect
PGDialect._get_server_version_info = lambda *args: (9, 2)

dh = dataHub()
db_con = dh.db_connect('postgre')

In [62]:
bs_max_dt = (
    pd.read_sql_query("""
        SELECT MAX(ls.game_date) 
        FROM nba.team_box_score AS bs
        LEFT JOIN nba.league_game_schedule AS ls on bs.game_id = ls.game_id
    """, db_con)
    ['max'][0]
    .strftime('%Y-%m-%d')
)

game_ids = (
    pd.read_sql_query(f"""
        SELECT game_id, game_date
        FROM nba.league_game_schedule
        WHERE game_date > '{bs_max_dt}'
            AND game_date <= current_date
    """, db_con)
)

trad_adv_lst = ['player_', 'team_']

for game_id in game_ids['game_id'][0:4]:
    game_id = '00' + str(int(game_id))

    dfs = []
    bsa = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id=game_id)
    if len(bsa.get_normalized_dict()['PlayerStats']) == 0:
        continue

    bst = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id)
    
    for el in [0, 1]:

        bst_col_order = pd.read_sql_query(f"SELECT column_name FROM util.table_column_order WHERE table_name = '{trad_adv_lst[el]}box_score_traditional' ORDER BY column_order", db_con)['column_name'].to_list()
        bsa_col_order = pd.read_sql_query(f"SELECT column_name FROM util.table_column_order WHERE table_name = '{trad_adv_lst[el]}box_score_advanced' ORDER BY column_order", db_con)['column_name'].to_list()
        
        bst_df = (
            bst
            .get_data_frames()[el]
            .rename(snakecase.convert, axis='columns')
            .drop_duplicates()
            .assign(game_id = lambda x: x['game_id'].astype('int'))
            .assign(min = lambda x: [int(re.sub(r'\..*', '', el)) if el is not None else None for el in x['min']])
            [bst_col_order]
        )

        bsa_df = (
            bsa
            .get_data_frames()[el]
            .rename(snakecase.convert, axis='columns')
            .drop_duplicates()
            .assign(game_id = lambda x: x['game_id'].astype('int'))
            [bsa_col_order]
        )
        
        jn_cols = list(set(bst_df.columns) & set(bsa_df.columns))
        df = bst_df.merge(bsa_df, how='left', on=jn_cols)
        dfs.append(df)

    # dfs[0].to_sql('player_box_score', db_con, schema='nba', index=False, if_exists='append')
    # dfs[1].to_sql('team_box_score', db_con, schema='nba', index=False, if_exists='append')

dfs[0]

,game_id,team_id,team_abbreviation,player_id,player_name,start_position,comment,min,fgm,fga,...,tm_tov_pct,efg_pct,ts_pct,usg_pct,e_usg_pct,e_pace,pace,pace_per40,poss,pie
0,42300151,1610612747,LAL,1629060,Rui Hachimura,F,,31.0,2.0,4.0,...,14.3,0.625,0.717,0.090,0.092,95.71,95.74,79.79,62,0.049
1,42300151,1610612747,LAL,2544,LeBron James,F,,40.0,10.0,16.0,...,21.2,0.719,0.742,0.291,0.296,95.03,94.23,78.53,80,0.146
2,42300151,1610612747,LAL,203076,Anthony Davis,C,,44.0,12.0,23.0,...,5.9,0.522,0.593,0.309,0.314,93.37,93.30,77.75,87,0.171
3,42300151,1610612747,LAL,1630559,Austin Reaves,G,,36.0,5.0,9.0,...,0.0,0.667,0.689,0.117,0.117,93.88,92.84,77.37,71,0.092
4,42300151,1610612747,LAL,1626156,D'Angelo Russell,G,,41.0,6.0,20.0,...,4.2,0.325,0.325,0.244,0.250,92.70,92.88,77.40,80,0.017
5,42300151,1610612747,LAL,203915,Spencer Dinwiddie,,,13.0,0.0,0.0,...,0.0,0.000,0.000,0.000,0.000,104.66,104.29,86.91,28,0.036
6,42300151,1610612747,LAL,1627752,Taurean Prince,,,20.0,4.0,7.0,...,0.0,0.643,0.698,0.190,0.195,95.12,94.04,78.37,40,0.174
7,42300151,1610612747,LAL,1629637,Jaxson Hayes,,,4.0,0.0,0.0,...,0.0,0.000,0.000,0.000,0.000,91.11,93.08,77.57,9,0.056
8,42300151,1610612747,LAL,1629216,Gabe Vincent,,,7.0,0.0,0.0,...,50.0,0.000,0.000,0.067,0.068,88.89,90.39,75.32,14,-0.093
9,42300151,1610612747,LAL,1631108,Max Christie,,DNP - Coach's Decision,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
10,42300151,1610612747,LAL,1641721,Maxwell Lewis,,DNP - Coach's Decision,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
11,42300151,1610612747,LAL,1629020,Jarred Vanderbilt,,DNP - Coach's Decision,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
12,42300151,1610612743,DEN,1629008,Michael Porter Jr.,F,,37.0,8.0,15.0,...,0.0,0.633,0.633,0.172,0.175,93.42,93.19,77.66,73,0.119
13,42300151,1610612743,DEN,203932,Aaron Gordon,F,,32.0,5.0,11.0,...,5.0,0.455,0.505,0.178,0.181,91.56,92.75,77.29,62,0.135
14,42300151,1610612743,DEN,203999,Nikola Jokić,C,,39.0,15.0,23.0,...,0.0,0.674,0.670,0.253,0.259,95.09,94.46,78.71,78,0.219
15,42300151,1610612743,DEN,203484,Kentavious Caldwell-Pope,G,,36.0,4.0,11.0,...,0.0,0.545,0.545,0.128,0.130,94.97,94.14,78.45,72,0.046
16,42300151,1610612743,DEN,1627750,Jamal Murray,G,,38.0,9.0,24.0,...,0.0,0.458,0.458,0.267,0.271,92.84,93.58,77.98,76,0.128
17,42300151,1610612743,DEN,1631212,Peyton Watson,,,13.0,3.0,6.0,...,25.0,0.667,0.667,0.222,0.237,101.46,99.99,83.32,29,0.008
18,42300151,1610612743,DEN,1631128,Christian Braun,,,17.0,1.0,5.0,...,0.0,0.200,0.200,0.116,0.120,95.19,95.73,79.78,35,0.000
19,42300151,1610612743,DEN,202704,Reggie Jackson,,,9.0,1.0,4.0,...,14.3,0.375,0.375,0.217,0.227,101.68,101.15,84.29,19,0.000
20,42300151,1610612743,DEN,203200,Justin Holiday,,,5.0,0.0,2.0,...,0.0,0.000,0.000,0.133,0.144,96.22,98.18,81.82,12,-0.071
21,42300151,1610612743,DEN,201599,DeAndre Jordan,,,8.0,1.0,1.0,...,0.0,1.000,1.064,0.111,0.112,91.80,91.91,76.60,16,0.155
22,42300151,1610612743,DEN,1630192,Zeke Nnaji,,DNP - Coach's Decision,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
23,42300151,1610612743,DEN,1629618,Jalen Pickett,,DNP - Coach's Decision,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
24,42300151,1610612743,DEN,1631124,Julian Strawther,,DNP - Coach's Decision,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN
25,42300151,1610612743,DEN,1641816,Hunter Tyson,,DNP - Coach's Decision,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000,0.000,NaN,NaN,NaN,0,NaN

In [33]:
df = (
    df_bs
    .drop_duplicates()
    .assign(game_id = lambda x: x['game_id'].astype('int'))
    .assign(min = lambda x: [int(re.sub(r'\..*', '', el)) if el is not None else None for el in x['min']])
    .merge(df_ls, how='left', on='game_id')
    [['game_id', 'game_date', 'team_id', 'team_abbreviation', 'player_id', 'player_name',
       'start_position', 'comment', 'min', 'fgm', 'fga', 'fg_pct', 'fg3_m',
       'fg3_a', 'fg3_pct', 'ftm', 'fta', 'ft_pct', 'pts', 'oreb', 'dreb', 'reb',
       'ast', 'stl', 'blk', 'to', 'pf', 'plus_minus', 'e_off_rating', 'off_rating',
       'e_def_rating', 'def_rating', 'e_net_rating', 'net_rating', 'ast_pct',
       'ast_tov', 'ast_ratio', 'oreb_pct', 'dreb_pct', 'reb_pct', 'tm_tov_pct',
       'efg_pct', 'ts_pct', 'usg_pct', 'e_usg_pct', 'e_pace', 'pace',
       'pace_per40', 'poss', 'pie']]
)

df.head()

,game_id,game_date,team_id,team_abbreviation,player_id,player_name,start_position,comment,min,fgm,...,tm_tov_pct,efg_pct,ts_pct,usg_pct,e_usg_pct,e_pace,pace,pace_per40,poss,pie
0,22301193,2024-04-14,1610612743,DEN,1629008,Michael Porter Jr.,F,,24.0,5.0,...,11.1,0.500,0.500,0.230,0.231,99.26,97.91,81.59,50,0.117
1,22301193,2024-04-14,1610612743,DEN,203932,Aaron Gordon,F,,26.0,4.0,...,6.3,0.667,0.788,0.169,0.171,100.81,98.45,82.04,53,0.152
2,22301193,2024-04-14,1610612743,DEN,203999,Nikola Jokić,C,,30.0,7.0,...,19.0,0.636,0.631,0.203,0.207,102.48,101.35,84.46,65,0.204
3,22301193,2024-04-14,1610612743,DEN,203484,Kentavious Caldwell-Pope,G,,24.0,5.0,...,18.2,0.917,0.854,0.127,0.128,102.67,100.51,83.76,53,0.121
4,22301193,2024-04-14,1610612743,DEN,1627750,Jamal Murray,G,,24.0,7.0,...,9.1,0.607,0.666,0.295,0.296,99.26,97.91,81.59,50,0.185

In [3]:
for gid in gids:
    print(gid)
    gid = '00' + str(gid)

    dfs = []
    bsa = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id=gid)
    if len(bsa.get_normalized_dict()['PlayerStats']) == 0:
        continue

    bst = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=gid)
    
    for el in [0, 1]:
        
        bst_df = bst.get_data_frames()[el]
        bsa_df = bsa.get_data_frames()[el]
        
        jn_cols = [el for el in bst_df.columns if el.endswith('ID')]
        dup_cols = list(set(bst_df.columns) & set(bsa_df.columns))
        drp_cols = [el for el in dup_cols if el not in jn_cols]
        
        df = (
            bst_df
            .drop(drp_cols, axis='columns')
            .merge(bsa_df, how='left', on=jn_cols)
            .rename(snakecase.convert, axis='columns')
        )
        
        dfs.append(df)

    dfs[0].to_sql('player_box_score', db_con, schema='nba', index=False, if_exists='append')
    dfs[1].to_sql('team_box_score', db_con, schema='nba', index=False, if_exists='append')

11300116
11300115
11300113
11300112
11300111
11300110
11300109
11300108
11300107
11300106
11300105
11300104
11300103
11300102
11300101
11300100
11300099
11300098
11300097
11300096
11300095
11300094
11300093
11300092
11300091
11300090
11300089
11300088
11300087
11300086
11300085
11300084
11300083
11300082
11300081
11300080
11300079
11300078
11300077
11300076
11300075
11300074
11300073
11300072
11300071
11300070
11300069
11300068
11300067
11300066
11300065
11300064
11300063
11300062
11300061
11300060
11300059
11300058
11300057
11300056
11300055
11300054
11300053
11300052
11300051
11300050
11300049
11300048
11300047
11300046
11300045
11300044
11300043
11300042
11300041
11300040
11300039
11300038
11300037
11300036
11300035
11300034
11300033
11300032
11300031
11300030
11300029
11300028
11300027
11300026
11300025
11300024
11300023
11300022
11300021
11300020
11300019
11300018
11300017
11300016
11300015
11300014
11300013
11300012
11300011
11300010
11300009
11300008
11300007
11300006
11300005
11300004
11300003
11300002
11300001
21201214
11200118
11200117
11200116
11200115
11200114
11200112
11200111
11200110
11200048
11200109
11200108
11200107
11200106
11200105
11200104
11200102
11200101
11200100
11200099
11200017
11200098
11200097
11200096
11200095
11200094
11200093
11200092
11200091
11200090
11200089
11200088
11200087
11200086
11200085
11200084
11200083
11200082
11200081
11200080
11200079
11200078
11200077
11200076
11200075
11200074
11200073
11200072
11200071
11200070
11200069
11200068
11200067
11200066
11200065
11200064
11200063
11200062
11200061
11200060
11200059
11200058
11200057
11200056
11200055
11200054
11200053
11200052
11200051
11200050
11200049
11200047
11200046
11200045
11200044
11200043
11200042
11200041
11200040
11200039
11200038
11200037
11200036
11200035
11200034
11200033
11200032
11200031
11200030
11200029
11200028
11200027
11200026
11200025
11200024
11200023
11200022
11200021
11200020
11200019
11200018
11200016
11200015
11200014
11200013
11200012
11200011
11200010
11200009
11200008
11200007
11200006
11200005
11200004
11200003
11200002
11200001
11100030
11100029
11100028
11100027
11100026
11100025
11100024
11100023
11100022
11100021
11100020
11100019
11100018
11100017
11100016
11100015
11100014
11100013
11100012
11100011
11100010
11100009
11100008
11100007
11100006
11100005
11100004
11100003
11100002
11100001
11000120
11000118
11000117
11000116
11000115
11000114
11000113
11000112
11000111
11000110
11000109
11000108
11000107
11000106
11000105
11000104
11000103
11000102
11000101
11000100
11000099
11000098
11000097
11000096
11000095
11000094
11000093
11000092
11000091
11000090
11000089
11000088
11000087
11000086
11000085
11000084
11000083
11000082
11000081
11000080
11000079
11000078
11000077
11000076
11000075
11000074
11000073
11000072
11000071
11000070
11000069
11000068
11000067
11000066
11000065
11000064
11000063
11000062
11000061
11000060
11000059
11000058
11000057
11000056
11000055
11000054
11000053
11000052
11000051
11000050
11000049
11000048
11000047
11000046
11000045
11000044
11000043
11000042
11000041
11000040
11000039
11000038
11000037
11000036
11000035
11000034
11000033
11000032
11000031
11000030
11000029
11000028
11000027
11000026
11000025
11000024
11000023
11000022
11000021
11000020
11000019
11000018
11000017
11000016
11000015
11000014
11000013
11000012
11000011
11000010
11000009
11000008
11000007
11000006
11000005
11000004
11000003
11000002
11000001
20900886
20900885
20900884
20900883
20900882
20900881
20900880
20900879
20900878
20900877
20900876
20900875
20900874
20900873
20900872
20900871
20900870
20900869
20900868
20900867
20900866
20900865
20900864
20900863
20900862
20900861
20900860
20900859
20900858
20900857
20900856
20900855
20900854
20900853
20900852
20900851
20900850
20900849
20900848
20900847
20900846
20900845
20900844
20900843
20900842
20900841
20900840
20900839
20900838
20900837
20900836
20900835
20900834
20900833
20900832
20900831
20900830
20900829
20900828
20900827
20900826
20900825
20900824
20900823
20900822
20900821
20900820
20900819
20900818
20900817
20900816
20900815
20900814
20900813
20900812
20900811
20900810
20900809
20900808
20900807
20900806
20900805
20900804
20900803
20900802
20900801
20900800
20900799
20900798
20900797
20900796
20900795
20900794
20900793
20900792
20900791
20900790
20900789
20900788
20900787
20900786
20900785
20900784
20900783
20900782
20900781
30900001
20900780
20900779
20900778
20900777
20900776
20900775
20900774
20900773
20900772
20900771
20900770
20900769
20900768
20900767
20900766
20900765
20900764
20900763
20900762
20900761
20900760
20900759
20900758
20900757
20900756
20900755
20900754
20900753
20900752
20900751
20900750
20900749
20900748
20900747
20900746
20900745
20900744
20900743
20900741
20900740
20900739
20900738
20900737
20900736
20900735
20900734
20900733
20900732
20900731
20900730
20900729
20900728
20900727
20900726
20900725
20900724
20900723
20900722
20900721
20900720
20900719
20900718
20900717
20900716
20900715
20900714
20900713
20900712
20900711
20900710
20900709
20900708
20900707
20900706
20900705
20900704
20900703
20900702
20900701
20900700
20900699
20900698
20900697
20900696
20900695
20900694
20900693
20900692
20900691
20900690
20900689
20900688
20900687
20900686
20900685
20900684
20900683
20900682
20900681
20900680
20900679
20900678
20900677
20900676
20900675
20900674
20900673
20900672
20900671
20900670
20900669
20900668
20900667
20900666
20900665
20900664
20900663
20900662
20900661
20900660
20900659
20900658
20900657
20900656
20900655
20900654
20900653
20900652
20900651
20900650
20900649
20900648
20900647
20900646
20900645
20900644
20900643
20900642
20900641
20900640
20900639
20900638
20900637
20900636
20900635
20900634
20900633
20900632
20900631
20900630
20900629
20900628
20900627
20900626
20900625
20900624
20900623
20900622
20900621
20900620
20900619
20900618
20900617
20900616
20900615
20900614
20900613
20900612
20900611
20900610
20900609
20900608
20900607
20900606
20900605
20900604
20900603
20900602
20900601
20900600
20900599
20900598
20900597
20900596
20900595
20900594
20900593
20900592
20900584
20900591
20900590
20900589
20900588
20900587
20900586
20900585
20900575
20900571
20900572
20900573
20900574
20900576
20900577
20900578
20900579
20900580
20900581
20900582
20900583
20900569
20900570
20900568
20900567
20900566
20900565
20900564
20900563
20900562
20900561
20900560
20900559
20900558
20900557
20900556
20900555
20900554
20900553
20900552
20900551
20900550
20900549
20900548
20900547
20900546
20900545
20900544
20900543
20900542
20900541
20900540
20900539
20900538
20900537
20900536
20900535
20900534
20900533
20900532
20900531
20900530
20900529
20900528
20900527
20900526
20900525
20900524
20900523
20900522
20900521
20900520
20900519
20900518
20900517
20900516
20900515
20900514
20900513
20900512
20900511
20900510
20900509
20900508
20900507
20900506
20900505
20900504
20900503
20900502
20900501
20900500
20900499
20900498
20900497
20900496
20900495
20900494
20900493
20900492
20900491
20900490
20900489
20900488
20900487
20900486
20900485
20900484
20900483
20900482
20900481
20900480
20900479
20900478
20900477
20900476
20900475
20900474
20900473
20900472
20900471
20900470
20900469
20900468
20900467
20900466
20900465
20900464
20900463
20900462
20900461
20900460
20900459
20900458
20900457
20900456
20900455
20900454
20900453
20900452
20900451
20900450
20900449
20900448
20900447
20900446
20900445
20900444
20900443
20900442
20900441
20900440
20900439
20900438
20900437
20900436
20900435
20900434
20900433
20900432
20900431
20900430
20900429
20900428
20900427
20900426
20900425
20900424
20900423
20900422
20900421
20900420
20900419
20900418
20900417
20900416
20900415
20900414
20900408
20900412
20900411
20900410
20900409
20900413
20900407
20900406
20900405
20900404
20900403
20900402
20900401
20900400
20900399
20900398
20900397
20900396
20900395
20900394
20900393
20900392
20900391
20900390
20900389
20900388
20900387
20900386
20900385
20900384
20900383
20900382
20900381
20900380
20900379
20900378
20900377
20900376
20900375
20900374
20900373
20900372
20900371
20900370
20900369
20900368
20900367
20900366
20900365
20900364
20900363
20900362
20900361
20900360
20900359
20900358
20900357
20900356
20900355
20900354
20900353
20900352
20900351
20900350
20900349
20900348
20900347
20900346
20900345
20900344
20900343
20900342
20900341
20900340
20900339
20900338
20900337
20900336
20900335
20900334
20900333
20900332
20900331
20900324
20900329
20900328
20900327
20900326
20900325
20900330
20900323
20900322
20900321
20900320
20900319
20900318
20900317
20900316
20900315
20900314
20900313
20900312
20900311
20900310
20900309
20900308
20900307
20900306
20900305
20900304
20900303
20900302
20900301
20900300
20900299
20900298
20900297
20900296
20900295
20900294
20900293
20900292
20900291
20900290
20900289
20900288
20900287
20900286
20900285
20900284
20900283
20900282
20900281
20900280
20900279
20900278
20900277
20900276
20900275
20900274
20900273
20900272
20900271
20900270
20900269
20900268
20900267
20900266
20900265
20900264
20900263
20900262
20900261
20900260
20900259
20900258
20900257
20900256
20900255
20900254
20900253
20900252
20900251
20900250
20900249
20900248
20900247
20900246
20900245
20900244
20900243
20900242
20900241
20900240
20900239
20900234
20900238
20900237
20900236
20900235
20900233
20900232
20900231
20900230
20900229
20900228
20900227
20900226
20900225
20900224
20900223
20900222
20900221
20900220
20900219
20900218
20900217
20900216
20900215
20900214
20900213
20900212
20900211
20900210
20900209
20900208
20900207
20900206
20900205
20900204
20900203
20900202
20900201
20900200
20900199
20900198
20900197
20900196
20900195
20900194
20900193
20900192
20900191
20900190
20900189
20900188
20900187
20900186
20900185
20900184
20900183
20900182
20900181
20900180
20900179
20900178
20900177
20900176
20900175
20900174
20900173
20900172
20900171
20900170
20900169
20900168
20900167
20900166
20900165
20900164
20900163
20900162
20900161
20900160
20900159
20900158
20900157
20900156
20900155
20900154
20900153
20900152
20900151
20900150
20900149
20900148
20900147
20900146
20900145
20900144
20900143
20900142
20900141
20900140
20900139
20900138
20900137
20900136
20900135
20900134
20900133
20900132
20900131
20900130
20900129
20900128
20900127
20900126
20900125
20900124
20900123
20900122
20900121
20900120
20900119
20900118
20900117
20900116
20900115
20900114
20900113
20900112
20900111
20900110
20900109
20900108
20900107
20900106
20900105
20900104
20900103
20900102
20900101
20900100
20900099
20900098
20900097
20900096
20900095
20900094
20900093
20900092
20900091
20900090
20900089
20900088
20900087
20900086
20900085
20900084
20900083
20900082
20900081
20900080
20900079
20900078
20900077
20900076
20900075
20900074
20900073
20900072
20900071
20900070
20900060
20900069
20900068
20900067
20900066
20900065
20900064
20900063
20900062
20900061
20900059
20900058
20900057
20900056
20900055
20900054
20900053
20900052
20900051
20900050
20900049
20900048
20900047
20900046
20900045
20900044
20900043
20900042
20900041
20900040
20900039
20900038
20900037
20900036
20900035
20900034
20900033
20900032
20900031
20900030
20900029
20900028
20900027
20900026
20900025
20900024
20900023
20900022
20900021
20900020
20900019
20900018
20900017
20900016
20900015
20900014
20900013
20900012
20900011
20900010
20900009
20900008
20900007
20900006
20900005
20900004
20900003
20900002
20900001
10900118
10900117
10900116
10900115
10900114
10900113
10900112
10900111
10900110
10900109
10900108
10900107
10900106
10900105
10900104
10900103
10900102
10900101
10900100
10900099
10900098
10900097
10900096
10900095
10900094
10900093
10900092
10900091
10900090
10900089
10900088
10900087
10900086
10900085
10900084
10900083
10900082
10900081
10900080
10900079
10900078
10900077
10900076
10900075
10900074
10900073
10900072
10900071
10900070
10900069
10900068
10900067
10900066
10900065
10900064
10900063
10900062
10900061
10900060
10900059
10900058
10900057
10900056
10900055
10900054
10900053
10900052
10900051
10900050
10900119
10900049
10900048
10900047
10900046
10900045
10900044
10900043
10900042
10900041
10900040
10900039
10900038
10900037
10900036
10900035
10900034
10900033
10900032
10900031
10900030
10900029
10900028
10900027
10900026
10900025
10900024
10900023
10900022
10900021
10900020
10900019
10900018
10900017
10900016
10900015
10900014
10900013
10900012
10900011
10900010
10900009
10900008
10900007
10900006
10900005
10900004
10900002
10900001

In [ ]:
request = get(f'https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2024/league/00_full_schedule_week_tbds.json')

# Dataframe object to be added to
df = pd.DataFrame()

# Loop through month elements
for month in request.json()['lscd']:
    df_row = pd.DataFrame(month['mscd']['g'])[['gid', 'gdte', 'an', 'ac', 'htm', 'vtm', 'v', 'h']]

    # Obtain home and away team info
    for col in ['h', 'v']:
        df_col = pd.DataFrame([[el['tid'], el['ta']] for el in df_row[col]])
        df_col.columns = ['home_team_id', 'home_team_slug'] if col == 'h' else ['away_team_id', 'away_team_slug']
        df_row = pd.concat([df_row, df_col], axis = 1)

    # Rename columns
    df_row = df_row.drop(columns=['v', 'h'])
    df_row = df_row.rename(columns={'gid':'game_id', 'gdte':'game_date', 'an':'arena', 'ac':'city', 'htm':'home_team_time', 'vtm':'away_team_time'})

    # Collate data
    df = pd.concat([df, df_row], ignore_index=True)

%view df df

# Cast date columns to_date & Create new columns
df['game_date'] = [parse(el).date() for el in df['game_date']]
df['slug_season'] = Season.current_season
df['slug_matchup'] = df['home_team_slug'] + ' vs. ' + df['away_team_slug']
df['slug_team_winner'] = None
df['slug_team_loser'] = None

key_dates = read_sql_query('SELECT * FROM util.key_dates', db_con)
df = sqldf("""
    SELECT 
        key_dates.season_type AS type_season, 
        df.*
    FROM df
    LEFT JOIN key_dates ON df.game_date >= key_dates.begin_date AND df.game_date <= key_dates.end_date
""", locals())[col_order]

# Write to database
df.to_sql('league_game_schedule', db_con, schema='nba', index=False, if_exists='append')
# return df
print('current_game_schedule has been updated\n\n')