# Future instruction
When it comes to updating database objects at the start of the season, I need to ensure each df fits with its corresponding db table.
In terms of "fit":
    <br>&emsp;If replace, ensure the new object contains all data and none is lost
    <br>&emsp;If append, ensure the df to be unioned is correct

In [1]:
import pandas as pd; pd.set_option('display.max_columns', 500)
from sqlalchemy.dialects.postgresql.base import PGDialect; PGDialect._get_server_version_info = lambda *args: (9, 2)
from dataHub import dataHub
dh = dataHub()

# db_con = dh.db_connect('cockroach')
db_con = dh.db_connect('postgre')
fty_con = dh.fty_con(db_con)

# Player Season Stats
Updated at the start of the season and can continue to be updated daily or weekly. This depends on how frequently the season_stat object is refreshed on the nba_api

In [2]:
dh.get_player_season_stats(db_con)

--------------------- nba.player_season_stats
player: 0 / 615
player: 4 / 615

,season,team_id,team_abbreviation,player_id,player_age,gp,gs,min,fgm,fga,fg_pct,fg3_m,fg3_a,fg3_pct,ftm,fta,ft_pct,pts,pf,oreb,dreb,reb,ast,stl,blk,tov
501,2023-24,1610612747,LAL,2544,39.0,71,71,2504.0,685,1269,0.540,149,363,0.410,303,404,0.750,1822,78,61,457,518,589,89,38,245
425,2023-24,1610612754,IND,204456,32.0,71,4,1291.0,330,593,0.556,18,44,0.409,49,62,0.790,727,79,36,155,191,390,72,8,108
426,2023-24,1610612753,ORL,204060,36.0,68,0,1169.0,99,227,0.436,70,161,0.435,28,34,0.824,296,88,18,124,142,203,43,5,67
427,2023-24,1610612738,BOS,204001,28.0,57,57,1690.0,388,752,0.516,110,293,0.375,259,302,0.858,1145,156,97,312,409,115,42,111,89
428,2023-24,1610612743,DEN,203999,29.0,79,79,2737.0,822,1411,0.583,83,231,0.359,358,438,0.817,2085,194,223,753,976,708,108,68,237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7581,2006-07,1610612740,NOK,101108,22.0,64,64,2353.0,381,871,0.437,50,143,0.350,292,357,0.818,1104,154,54,226,280,569,118,3,161
7584,2005-06,1610612739,CLE,2544,21.0,79,79,3361.0,875,1823,0.480,127,379,0.335,601,814,0.738,2478,181,75,481,556,521,123,66,260
7583,2005-06,1610612740,NOK,101108,21.0,78,78,2808.0,407,947,0.430,50,177,0.282,394,465,0.847,1258,218,61,339,400,611,175,6,183
7585,2004-05,1610612739,CLE,2544,20.0,80,80,3388.0,795,1684,0.472,108,308,0.351,477,636,0.750,2175,146,111,477,588,577,177,52,262
7586,2003-04,1610612739,CLE,2544,19.0,79,79,3120.0,622,1492,0.417,63,217,0.290,347,460,0.754,1654,149,99,333,432,465,130,58,273

# Player Info
Updated once at the start of each season

In [2]:
dh.get_player_info(db_con)

--------------------- nba.player_info
player: 0 / 615
player: 4 / 615

,player_id,first_name,last_name,display_first_last,display_last_comma_first,display_fi_last,player_slug,birthdate,school,country,last_affiliation,height_cm,weight_kg,season_exp,jersey,position,rosterstatus,games_played_current_season_flag,team_id,team_name,team_abbreviation,team_code,team_city,playercode,from_year,to_year,dleague_flag,nba_flag,games_played_flag,draft_year,draft_round,draft_number,greatest_75_flag
5,1630173,Precious,Achiuwa,Precious Achiuwa,"Achiuwa, Precious",P. Achiuwa,precious-achiuwa,1999-09-19T00:00:00,Memphis,Nigeria,Memphis/Nigeria,203.20,110.224,4,5,Forward,Active,Y,1610612752,Knicks,NYK,knicks,New York,precious_achiuwa,2020,2024,N,Y,Y,2020,1,20,N
6,203500,Steven,Adams,Steven Adams,"Adams, Steven",S. Adams,steven-adams,1993-07-20T00:00:00,Pittsburgh,New Zealand,Pittsburgh/New Zealand,210.82,120.203,10,12,Center,Active,Y,1610612745,Rockets,HOU,rockets,Houston,steven_adams,2013,2024,N,Y,Y,2013,1,12,N
7,1628389,Bam,Adebayo,Bam Adebayo,"Adebayo, Bam",B. Adebayo,bam-adebayo,1997-07-18T00:00:00,Kentucky,USA,Kentucky/USA,205.74,115.667,7,13,Center-Forward,Active,Y,1610612748,Heat,MIA,heat,Miami,bam_adebayo,2017,2024,N,Y,Y,2017,1,14,N
8,1630534,Ochai,Agbaji,Ochai Agbaji,"Agbaji, Ochai",O. Agbaji,ochai-agbaji,2000-04-20T00:00:00,Kansas,USA,Kansas/USA,195.58,97.523,2,30,Guard,Active,Y,1610612761,Raptors,TOR,raptors,Toronto,ochai_agbaji,2022,2024,Y,Y,Y,2022,1,14,N
9,1630583,Santi,Aldama,Santi Aldama,"Aldama, Santi",S. Aldama,santi-aldama,2001-01-10T00:00:00,Loyola-Maryland,Spain,Loyola-Maryland/Spain,213.36,97.523,3,7,Forward-Center,Active,Y,1610612763,Grizzlies,MEM,grizzlies,Memphis,santi_aldama,2021,2024,Y,Y,Y,2021,1,30,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5056,1641792,Joey,Hauser,Joey Hauser,"Hauser, Joey",J. Hauser,joey-hauser,1999-07-17,Michigan State,USA,Michigan State/USA,NaN,NaN,0,,,Inactive,N,0,,,,,joey_hauser,None,None,N,N,N,Undrafted,Undrafted,Undrafted,N
5057,1641935,Jarkel,Joiner,Jarkel Joiner,"Joiner, Jarkel",J. Joiner,jarkel-joiner,1999-05-21,North Carolina State,USA,North Carolina State/USA,NaN,NaN,0,,,Inactive,N,0,,,,,jarkell_joiner,None,None,N,N,N,Undrafted,Undrafted,Undrafted,N
5058,1641795,Taevion,Kinsey,Taevion Kinsey,"Kinsey, Taevion",T. Kinsey,taevion-kinsey,2000-03-10,Marshall,USA,Marshall/USA,NaN,NaN,0,,,Inactive,N,0,,,,,taevion_kinsey,None,None,N,N,N,Undrafted,Undrafted,Undrafted,N
5059,1641861,Nick,Ongenda,Nick Ongenda,"Ongenda, Nick",N. Ongenda,nick-ongenda,2000-09-29,DePaul,South Africa,DePaul/South Africa,NaN,NaN,0,,,Inactive,N,0,,,,,nick_ongenda,None,None,N,N,N,Undrafted,Undrafted,Undrafted,N
5060,1641869,Malachi,Smith,Malachi Smith,"Smith, Malachi",M. Smith,malachi-smith,1999-12-06,Gonzaga,USA,None,NaN,NaN,0,,,Inactive,N,0,,,,,malachi_smith,None,None,N,N,N,Undrafted,Undrafted,Undrafted,N

# Player Game Log
Updated at the start of the season and daily for the rest of the season. Remember to control for season type list ['Pre Season', 'Regular Season', etc....]

In [28]:
# dh.get_player_game_log(db_con)

# Game Schedule
Use update_historical_game_schedule() to update records from last season. Use get_next_game_schedule() to obtain schedule for upcoming season. Run both functions at the start of each season

In [2]:
dh.update_past_game_schedule(db_con)

--------------------- nba.historical_league_game_schedule

,season_type,season,game_id,game_date,matchup,team_winner,team_loser
0,Pre Season,2009-10,10900001.0,2009-09-30,DEN @ UTA,UTA,DEN
1,Pre Season,2009-10,10900002.0,2009-10-01,CHI @ IND,CHI,IND
2,Pre Season,2009-10,10900004.0,2009-10-03,NYK vs. NJN,NYK,NJN
3,Pre Season,2009-10,10900005.0,2009-10-03,LAC @ GSW,GSW,LAC
4,Pre Season,2009-10,10900006.0,2009-10-03,MIL @ MIN,MIN,MIL
...,...,...,...,...,...,...,...
21703,Playoffs,2023-24,42300402.0,2024-06-09,DAL @ BOS,BOS,DAL
21704,Playoffs,2023-24,42300403.0,2024-06-12,BOS @ DAL,BOS,DAL
21705,Playoffs,2023-24,42300404.0,2024-06-14,DAL vs. BOS,DAL,BOS
21706,Playoffs,2023-24,42300405.0,2024-06-17,BOS vs. DAL,BOS,DAL
21707,All Star,2023-24,32300001.0,2024-02-18,EST vs. WST,EST,WST

In [3]:
dh.get_next_game_schedule(db_con)

,season_type,season,game_id,game_date,matchup,team_winner,team_loser
0,Regular Season,2024-25,0022400455,2025-01-01,DET vs. ORL,None,None
1,Regular Season,2024-25,0022400456,2025-01-01,WAS vs. CHI,None,None
2,Regular Season,2024-25,0022400457,2025-01-01,MIA vs. NOP,None,None
3,Regular Season,2024-25,0022400458,2025-01-01,NYK vs. UTA,None,None
4,Regular Season,2024-25,0022400459,2025-01-01,TOR vs. BKN,None,None
...,...,...,...,...,...,...,...
1277,Regular Season,2024-25,0022400450,2024-12-31,IND vs. MIL,None,None
1278,Regular Season,2024-25,0022400451,2024-12-31,SAS vs. LAC,None,None
1279,Regular Season,2024-25,0022400452,2024-12-31,OKC vs. MIN,None,None
1280,Regular Season,2024-25,0022400453,2024-12-31,PHX vs. MEM,None,None
1281,Regular Season,2024-25,0022400454,2024-12-31,LAL vs. CLE,None,None

# Box Scores

In [2]:
# dh.get_box_score(db_con)

player and team box_score have been updated

# Team Roster
Updated at the start of the season and after trade deadline

In [2]:
dh.get_team_roster(db_con)

--------------------- nba.team_roster
team: 0 / 30
team: 4 / 30

,season,team_slug,team_id,player_id,player,nickname,player_slug,num,position,height_cm,weight_kg,birth_date,age,exp,school,how_acquired
0,2024-25,ATL,1610612737,1630811,Keaton Wallace,Keaton,keaton-wallace,None,G,190.50,83.915,"FEB 26, 1999",25.0,R,Texas-San Antonio,Signed on 09/29/23
1,2024-25,ATL,1610612737,1630552,Jalen Johnson,Jalen,jalen-johnson,1,F,203.20,99.338,"DEC 18, 2001",22.0,3,Duke,#20 Pick in 2021 Draft
2,2024-25,ATL,1610612737,1641754,Seth Lundy,Seth,seth-lundy,3,G-F,193.04,99.791,"APR 02, 2000",24.0,1,Penn State,#46 Pick in 2023 Draft
3,2024-25,ATL,1610612737,1641723,Kobe Bufkin,Kobe,kobe-bufkin,4,G,193.04,88.451,"SEP 21, 2003",21.0,1,Michigan,#15 Pick in 2023 Draft
4,2024-25,ATL,1610612737,1642258,Zaccharie Risacher,Zaccharie,zaccharie-risacher,10,F,203.20,90.719,"APR 08, 2005",19.0,R,JL Bourg-en-Bresse,#1 Pick in 2024 Draft
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,2024-25,CHA,1610612766,1630544,Tre Mann,Tre,tre-mann,23.0,G,190.50,80.740,2001-02-03,23.0,3,Florida,Traded from OKC on 02/08/24
665,2024-25,CHA,1610612766,1641706,Brandon Miller,Brandon,brandon-miller,24.0,F,200.66,90.719,2002-11-22,21.0,1,Alabama,#2 Pick in 2023 Draft
666,2024-25,CHA,1610612766,1631217,Moussa Diabaté,Moussa,moussa-diabaté,25.0,F,205.74,95.255,2002-01-21,22.0,2,Michigan,Signed on 07/31/24
667,2024-25,CHA,1610612766,203552,Seth Curry,Seth,seth-curry,30.0,G,185.42,83.915,1990-08-23,34.0,10,Duke,Traded from DAL on 02/08/24
668,2024-25,CHA,1610612766,201959,Taj Gibson,Taj,taj-gibson,67.0,F,205.74,105.235,1985-06-24,39.0,15,Southern California,Signed on 07/13/24

# Transactions

In [26]:
# dh.get_transactions(db_con)

# Fantasy data instruction

# Free Agents
Updated daily

In [8]:
# dh.fty_get_free_agents(fty_con, db_con)

# Fantasy Team Rosters
Updated daily

In [ ]:
# dh.fty_get_league_schedule(fty_con, db_con)

In [ ]:
# dh.fty_get_competitor_roster(fty_con, db_con)

In [ ]:
# dh.fty_get_recent_activity(fty_con, db_con)

In [ ]:
# dh.fty_get_matchup_box_score(fty_con, db_con)