# Future instruction
When it comes to updating database objects at the start of the season, I need to ensure each df fits with its corresponding db table.
In terms of "fit":
    <br>&emsp;If replace, ensure the new object contains all data and none is lost
    <br>&emsp;If append, ensure the df to be unioned is correct

In [1]:
import pandas as pd; pd.set_option('display.max_columns', 500)
from dataHub import dataHub
dh = dataHub()

postgre_con = dh.db_connect('postgre')
fty_con = dh.fty_api_con()

# Player Season Stats
Updated at the start of the season and can continue to be updated daily or weekly. This depends on how frequently the season_stat object is refreshed on the nba_api

In [2]:
player_season_stats = dh.get_player_season_stats(postgre_con)
player_season_stats.head()

--------------------- player season stats

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

# Player Info
Updated once at the start of each season

In [3]:
player_info = dh.get_player_info(postgre_con)
player_info.head()

--------------------- player_info
player: 0 / 535

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

# Player Game Log
Updated at the start of the season and daily for the rest of the season. Remember to control for season type list ['Pre Season', 'Regular Season', etc....]

In [4]:
player_game_log = dh.get_player_game_log(postgre_con)
player_game_log.head()

--------------------- player_game_log

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

# Game Schedule
Use update_historical_game_schedule() to update records from last season. Use get_next_game_schedule() to obtain schedule for upcoming season. Run both functions at the start of each season

In [5]:
hist_game_schedule = dh.update_historical_game_schedule(postgre_con)
hist_game_schedule.head()

--------------------- historical_league_game_schedule
historical_game_schedule has been updated

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,season_type,type_season,slug_season,game_id,game_date,slug_matchup,slug_team_winner,slug_team_loser,number_game_day
0,22021,1.610613e+09,BKN,Brooklyn Nets,0022100001,2021-10-19,BKN @ MIL,L,240.0,37.0,84.0,0.440,17.0,32.0,0.531,13.0,23.0,0.565,5.0,39.0,44.0,19.0,3.0,9.0,13.0,17.0,104.0,-23.0,1.0,Regular Season,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22021,1.610613e+09,MIL,Milwaukee Bucks,0022100001,2021-10-19,MIL vs. BKN,W,240.0,48.0,105.0,0.457,17.0,45.0,0.378,14.0,18.0,0.778,13.0,41.0,54.0,25.0,8.0,9.0,8.0,19.0,127.0,23.0,1.0,Regular Season,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22021,1.610613e+09,GSW,Golden State Warriors,0022100002,2021-10-19,GSW @ LAL,W,240.0,41.0,93.0,0.441,14.0,39.0,0.359,25.0,30.0,0.833,9.0,41.0,50.0,30.0,9.0,2.0,17.0,18.0,121.0,7.0,1.0,Regular Season,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,22021,1.610613e+09,LAL,Los Angeles Lakers,0022100002,2021-10-19,LAL vs. GSW,L,240.0,45.0,95.0,0.474,15.0,42.0,0.357,9.0,19.0,0.474,5.0,40.0,45.0,21.0,7.0,4.0,18.0,25.0,114.0,-7.0,1.0,Regular Season,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22021,1.610613e+09,CHA,Charlotte Hornets,0022100003,2021-10-20,CHA vs. IND,W,240.0,46.0,107.0,0.430,13.0,31.0,0.419,18.0,27.0,0.667,12.0,34.0,46.0,29.0,9.0,5.0,8.0,21.0,123.0,1.0,1.0,Regular Season,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
next_game_schedule = dh.get_next_game_schedule(postgre_con)
next_game_schedule.head()

current_game_schedule has been updated

,type_season,slug_season,game_id,game_date,slug_matchup,slug_team_winner,slug_team_loser,number_game_day
0,None,2022-23,0022200547,2023-01-01,MEM vs. SAC,None,None,None
1,None,2022-23,0022200548,2023-01-01,MIL vs. WAS,None,None,None
2,None,2022-23,0022200549,2023-01-01,DEN vs. BOS,None,None,None
3,None,2022-23,0022200550,2023-01-02,NYK vs. PHX,None,None,None
4,None,2022-23,0022200551,2023-01-02,CHA vs. LAL,None,None,None

# Team Roster
Updated at the start of the season and after trade deadline

In [7]:
team_roster = dh.get_team_roster(postgre_con)
team_roster.head()

--------------------- commonteamroster
team: 0 / 30
team: 5 / 30
team: 10 / 30
team: 15 / 30
team: 20 / 30
team: 25 / 30
team: 29 / 30
historical_game_schedule has been updated

,slug_season,season,team_slug,team_id,player_id,player,nickname,player_slug,num,position,height,weight,birth_date,age,exp,school,how_acquired
0,2022-23,2022,ATL,1610612737,1631495,Donovan Williams,Donovan,donovan-williams,None,G,6-6,190,"SEP 06, 2001",21.0,R,UNLV,None
1,2022-23,2022,ATL,1610612737,1628981,Bruno Fernando,Bruno,bruno-fernando,0,F-C,6-10,240,"AUG 15, 1998",24.0,3,Maryland,Traded from HOU on 02/09/23
2,2022-23,2022,ATL,1610612737,1630552,Jalen Johnson,Jalen,jalen-johnson,1,F,6-8,219,"DEC 18, 2001",21.0,1,Duke,#20 Pick in 2021 Draft
3,2022-23,2022,ATL,1610612737,1630235,Trent Forrest,Trent,trent-forrest,2,G,6-4,210,"JUN 12, 1998",25.0,2,Florida State,Signed on 08/08/22
4,2022-23,2022,ATL,1610612737,1628988,Aaron Holiday,Aaron,aaron-holiday,3,G,6-0,185,"SEP 30, 1996",26.0,4,UCLA,None

# Fantasy data instruction
Do this part later

# Free Agents
Updated daily

In [8]:
free_agents = dh.fty_get_free_agents(fty_con.free_agents(size=1000), postgre_con)
free_agents.head()

free_agents has been updated

   player_id        player_name player_team player_status player_position
0       3468  Russell Westbrook         LAC        ACTIVE              PG
1    4395725        Tyler Herro         MIA        ACTIVE              SG
2       6440      Tobias Harris         PHL        ACTIVE              SF
3       4251        Paul George         LAC           OUT              SF
4    3058254     Christian Wood         DAL        ACTIVE               C

# Fantasy Team Rosters
Updated daily

In [9]:
fty_con.teams

[Team(Philly 5 ⭐️ Men),
 Team(El Barto ),
 Team(Hawkes Bay Bombers),
 Team(Ashhurst Beasthunters),
 Team(Naboo Fred-Ball),
 Team(Capital city Cantz),
 Team(Manawatu McGregor ),
 Team(Taranaki  Thunder)]